# Generated by Django 4.1.7 on 2023-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0002_alter_entity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название'),
        ),
    ]
