# Generated by Django 4.2.1 on 2023-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0002_alter_doc_entity_alter_entity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='entity',
            field=models.ManyToManyField(blank=True, default=None, related_name='entities', to='segregator.entity', verbose_name='Оглавления'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='document',
            field=models.ManyToManyField(blank=True, default=None, related_name='documents', to='segregator.doc', verbose_name='файлы'),
        ),
    ]
