# Generated by Django 4.1.7 on 2023-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0003_alter_entity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
    ]
