# Generated by Django 4.2.1 on 2023-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0003_alter_doc_entity_alter_entity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='body',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
