# Generated by Django 4.1.7 on 2023-02-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0004_alter_entity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип связи')),
            ],
            options={
                'verbose_name': 'Тип связи',
                'verbose_name_plural': 'Типы связей',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to='segregator.entity', verbose_name='Связь от')),
                ('rel_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to', to='segregator.entity', verbose_name='Связь к')),
                ('rel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_types', to='segregator.relationtype', verbose_name='Тип связи')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
    ]
