# Generated by Django 4.2.1 on 2023-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0005_remove_entity_document_remove_doc_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(),
        ),
    ]
