# Generated by Django 4.2.1 on 2023-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0006_alter_entity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
