# Generated by Django 4.2.1 on 2023-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segregator', '0007_alter_entity_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='doc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
